// <auto-generated />
using System;
using CrmIgreja.api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmIgreja.api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326230327_AdicionarTabelaCheckin")]
    partial class AdicionarTabelaCheckin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmIgreja.api.Models.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("dataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("dataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("dataInicio");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.EventoToken", b =>
                {
                    b.Property<int>("eventoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("eventoid")
                        .HasColumnType("integer");

                    b.Property<bool>("isRevogado")
                        .HasColumnType("boolean");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("eventoId");

                    b.HasIndex("eventoid");

                    b.HasIndex("tokenHash", "isRevogado");

                    b.ToTable("EventoToken");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.Membro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("membroId")
                        .HasColumnType("integer");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("refreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("senhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("membroId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.EventoToken", b =>
                {
                    b.HasOne("CrmIgreja.api.Models.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("eventoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.Usuario", b =>
                {
                    b.HasOne("CrmIgreja.api.Models.Membro", "Membro")
                        .WithOne("Usuario")
                        .HasForeignKey("CrmIgreja.api.Models.Usuario", "membroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("CrmIgreja.api.Models.Membro", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
